application:
  name: hello_flask
  project: hello-flask
  publicly_accessible: true
  organization: QoveryCommunity
routers:
- name: main
  routes:
  - application_name: hello_flask
    paths:
    - /
